services:
  php:
    image: tigitz/phpspellchecker:${PHP_VERSION:-8.4}
    user: 1001:1001
    build:
      context: docker/php
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
    volumes:
      - .:/usr/src/myapp
      - ./composer/cache:/root/composer/cache
    environment:
      - LANG=en_US.UTF-8
      - COMPOSER_CACHE_DIR=/root/composer/cache
    depends_on:
      - languagetools
      - jamspell

  jamspell:
    image: tigitz/jamspell

  languagetools:
    image: silviof/docker-languagetool
